spring:
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/amenity_reservation
    username: dev
    password: Portmore254@
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
